language: python
python:
  - "2.7"
install:
  # Install conda
  - pip install conda
  # install deps
  - conda init
  - conda update conda --yes
  - deps='pip pandas'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
script:
  - pytest --doctest-modules
