language: python
python:
  - "2.7"
sudo: required
virtualenv:
    system_site_packages: true
install:
  #- pip install requests[security]
  - sudo pip install -r requirements.txt
script:
  #- pytest --doctest-modules
  - python -m doctest python-scripts/python1.py
