language: python
python:
  - "2.7"
#virtualenv:
#    system_site_packages: true
install:
  - sudo pip install -r requirements.txt
script:
  #- pytest --doctest-modules
  - python -m doctest python-scripts/python1.py
